# Generated by Django 4.1 on 2023-09-20 14:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_mac', models.CharField(max_length=50)),
                ('sensor_type', models.CharField(max_length=50)),
                ('sensor_value', models.FloatField()),
                ('rec_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('-rec_date',),
            },
        ),
        migrations.CreateModel(
            name='SmartPlugRec',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestmp', models.DateTimeField(unique=True)),
                ('response', models.JSONField()),
            ],
            options={
                'db_table': 'plug_info',
                'ordering': ['-timestmp'],
            },
        ),
    ]
