# Generated by Django 4.2 on 2023-09-19 05:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_mac', models.CharField(max_length=50)),
                ('sensor_type', models.CharField(max_length=50)),
                ('sensor_value', models.FloatField()),
                ('rec_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('-rec_date',),
            },
        ),
    ]
