# Generated by Django 4.2 on 2023-09-21 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartplugrec',
            name='timestmp',
            field=models.CharField(max_length=50),
        ),
    ]
