# Generated by Django 4.1 on 2023-09-20 13:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beverage',
            fields=[
                ('id', models.TextField(blank=True, primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True)),
                ('cde', models.FloatField(blank=True)),
                ('unit', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'beverage',
            },
        ),
        migrations.CreateModel(
            name='CdeTransport',
            fields=[
                ('id', models.TextField(blank=True, primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True)),
                ('cde', models.FloatField(blank=True)),
                ('unit', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'cde_transport',
            },
        ),
        migrations.CreateModel(
            name='CfpClass',
            fields=[
                ('class_id', models.TextField(blank=True, primary_key=True, serialize=False)),
                ('class_name', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'cfp_class',
            },
        ),
        migrations.CreateModel(
            name='EggProds',
            fields=[
                ('id', models.TextField(blank=True, primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True)),
                ('cde', models.FloatField(blank=True)),
                ('unit', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'egg_prods',
            },
        ),
        migrations.CreateModel(
            name='ElecDeviceConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('watt', models.IntegerField(blank=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'elec_device_consumption',
            },
        ),
        migrations.CreateModel(
            name='Energy',
            fields=[
                ('id', models.TextField(blank=True, primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True)),
                ('cde', models.FloatField(blank=True)),
                ('unit', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'energy',
            },
        ),
        migrations.CreateModel(
            name='LactoseProds',
            fields=[
                ('id', models.TextField(blank=True, primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True)),
                ('cde', models.FloatField(blank=True)),
                ('unit', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'lactose_prods',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('-pub_date',),
            },
        ),
        migrations.CreateModel(
            name='TimeElecRates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField(unique=True)),
                ('effect_date', models.IntegerField()),
                ('rates', models.FloatField(blank=True)),
            ],
            options={
                'db_table': 'time_elec_rates',
                'unique_together': {('desc', 'effect_date')},
            },
        ),
        migrations.CreateModel(
            name='SummerC3Rates',
            fields=[
                ('h_id', models.AutoField(primary_key=True, serialize=False)),
                ('wday_rate', models.ForeignKey(db_column='wday_rate', on_delete=django.db.models.deletion.CASCADE, related_name='summerc3rates_wday', to='mainsite.timeelecrates', to_field='desc')),
                ('wend_rate', models.ForeignKey(db_column='wend_rate', on_delete=django.db.models.deletion.CASCADE, related_name='summerc3rates_wend', to='mainsite.timeelecrates', to_field='desc')),
            ],
            options={
                'db_table': 'summer_c3_rates',
            },
        ),
        migrations.CreateModel(
            name='SummerC2Rates',
            fields=[
                ('h_id', models.AutoField(primary_key=True, serialize=False)),
                ('wday_rate', models.ForeignKey(db_column='wday_rate', on_delete=django.db.models.deletion.CASCADE, related_name='summerc2rates_wday', to='mainsite.timeelecrates', to_field='desc')),
                ('wend_rate', models.ForeignKey(db_column='wend_rate', on_delete=django.db.models.deletion.CASCADE, related_name='summerc2rates_wend', to='mainsite.timeelecrates', to_field='desc')),
            ],
            options={
                'db_table': 'summer_c2_rates',
            },
        ),
        migrations.CreateModel(
            name='CfpSubClass',
            fields=[
                ('sub_class_id', models.TextField(blank=True, primary_key=True, serialize=False)),
                ('sub_class_name', models.TextField(blank=True)),
                ('class_id', models.ForeignKey(blank=True, db_column='class_id', on_delete=django.db.models.deletion.DO_NOTHING, to='mainsite.cfpclass')),
            ],
            options={
                'db_table': 'cfp_sub_class',
            },
        ),
        migrations.CreateModel(
            name='CfpSosClass',
            fields=[
                ('cfp_sos_class_id', models.TextField(blank=True, primary_key=True, serialize=False)),
                ('cfp_sos_class_name', models.TextField(blank=True)),
                ('cfp_sub_class', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mainsite.cfpsubclass')),
            ],
            options={
                'db_table': 'cfp_sos_class',
            },
        ),
        migrations.CreateModel(
            name='C3Rates',
            fields=[
                ('h_id', models.AutoField(primary_key=True, serialize=False)),
                ('wday_rate', models.ForeignKey(db_column='wday_rate', on_delete=django.db.models.deletion.CASCADE, related_name='c3rates_wday', to='mainsite.timeelecrates', to_field='desc')),
                ('wend_rate', models.ForeignKey(db_column='wend_rate', on_delete=django.db.models.deletion.CASCADE, related_name='c3rates_wend', to='mainsite.timeelecrates', to_field='desc')),
            ],
            options={
                'db_table': 'c3_rates',
            },
        ),
        migrations.CreateModel(
            name='C2Rates',
            fields=[
                ('h_id', models.AutoField(primary_key=True, serialize=False)),
                ('wday_rate', models.ForeignKey(db_column='wday_rate', on_delete=django.db.models.deletion.CASCADE, related_name='C2Rates_wday', to='mainsite.timeelecrates', to_field='desc')),
                ('wend_rate', models.ForeignKey(db_column='wend_rate', on_delete=django.db.models.deletion.CASCADE, related_name='C2Rates_wend', to='mainsite.timeelecrates', to_field='desc')),
            ],
            options={
                'db_table': 'c2_rates',
            },
        ),
    ]
